-- Veritabanı tablo yapısını buraya ekleyin
-- Örnek olarak:
-- CREATE TABLE muzikler (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     ad VARCHAR(255) NOT NULL,
--     sanatci VARCHAR(255),
--     album VARCHAR(255),
--     tarih DATETIME DEFAULT CURRENT_TIMESTAMP
-- );
